name: khubzati
description: A monorepo for khubzati packages
version: 1.0.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  melos: ^3.0.0
  localization: ^2.1.1
  cupertino_icons: ^1.0.6
  auto_route: ^9.2.2
  lottie: ^3.1.3
  another_flutter_splash_screen: ^1.2.1
  flutter_gen: ^5.8.0
  flutter_svg: ^2.0.11
  device_preview: ^1.2.0
  easy_localization: ^3.0.7
  injectable: ^2.5.0
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  jwt_decoder: ^2.0.1
  dio: ^5.7.0
  shared_preferences: ^2.3.0
  firebase_core: ^3.6.0
  streaming_shared_preferences: ^2.0.0
  firebase_auth: ^5.2.0
  flutter_share: ^2.0.0
  phone_form_field: ^9.2.8
  dio_cache_interceptor: ^3.5.0
  awesome_dio_interceptor: ^1.2.0
  retrofit: ^4.4.1
  get_it: ^8.0.2
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  file_picker: ^8.1.7
  intl_phone_field: ^3.2.0
  grouped_list: ^6.0.0
  expansion_widget: ^0.1.0
  intl: ^0.20.2
  flutter_form_builder: ^10.2.0
  pin_code_fields: ^8.0.1
  flutter_secure_storage: ^4.2.1
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.0
  sms_autofill: ^2.2.0 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  injectable_generator: ^2.6.2
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/splash/
    - assets/translations/
    - assets/fonts/
    - assets/gif/